### ISSUE TITLE
日语学习计划

### ISSUE THREAD

**Issue by neteroster** [neteroster/blog#9]
# 日语学习计划

版本：草稿 05（修订 2023-02-09）激进

## 基本目标

通过自学，达到基本掌握现代日语的语法框架、具备一定日语词汇量、能够使用日语进行基本的日常交流的水平。

## 详细目标

最晚在 **2023 年 12 月 31 日** 之前达到 JLPT-N2 水平，并在此之后选择适当时机参加 JLPT-N2 测试。

### 日语语法学习

* [日语基础语法部分](https://github.com/neteroster/blog/blob/main/%E6%97%A5%E8%AF%AD%E8%AF%AD%E6%B3%95%E4%B9%8B%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.md)（已完成）
* [日语语法化与形式名词部分](https://github.com/neteroster/blog/blob/main/%E6%97%A5%E8%AF%AD%E8%AF%AD%E6%B3%95%E4%B9%8B%E8%AF%AD%E6%B3%95%E5%8C%96%E4%B8%8E%E5%BD%A2%E5%BC%8F%E5%90%8D%E8%AF%8D.md)（已完成）
* [日语语法之命题与情态](https://github.com/neteroster/blog/blob/main/%E6%97%A5%E8%AF%AD%E8%AF%AD%E6%B3%95%E4%B9%8B%E5%91%BD%E9%A2%98%E4%B8%8E%E6%83%85%E6%80%81.md) （进行中）
* [日语语法杂项记录](https://github.com/neteroster/blog/blob/main/%E6%97%A5%E8%AF%AD%E8%AF%AD%E6%B3%95%E4%B9%8B%E6%9D%82%E9%A1%B9.md)（不定时更新）

**Comment by neteroster** [comment]
基于两个理由，本计划暂时性地终止。

1. 没有充分的可用时间以完成目标任务。
2. 自 2023 年初大语言模型（LLMs）在中日互译的成就以及其未来可能的发展使得本计划的必要性降低。

**Comment by 3126058535** [comment]
我已成功收到您的邮件
